### ISSUE TITLE
Tabu documentation of timeout and num_reads inaccurate, not clear what is happening.

### ISSUE THREAD

**Issue by jackraymond** [dwavesystems/dwave-samplers#25]
```
samples = tabu_sampler.sample_ising(h = {'a': -0.5, 'b': 1.0}, J = {'ab ': -1},num_restarts = 0,num_reads=100,timeout=1000)
```
We anticipate the runtime of this algorithm to be close to timeout*num_reads according to the MST2 reference (no restarts - STS(), which should run until a timeout condition is met). However, it seems to be more than 2 orders of magnitude shorter and basically independent of timeout.

Perhaps a max number of iterations (z) is silently hardcoded per restart? I've varied, num_restarts, tenure, num_reads and complexity (size and level of frustration) of the ising model without recovering the expected behavior.

**Comment by jackraymond** [comment]
https://github.com/dwavesystems/dwave-samplers/blob/2dc692a92ca7f56c61f17de0440b488a3aed3bb9/dwave/samplers/tabu/src/tabu_search.cpp#L80

Seems like z is hardcoded and it shouldn't be, this should be an exposed parameter and also a useful alternative to timeout

**Comment by jackraymond** [comment]
I'll make a pull request to correct this.

**Comment by arcondello** [comment]
Closed by https://github.com/dwavesystems/dwave-samplers/pull/26
